export const BASE_URL = 'http://localhost:8000'
export const POKEMON_LIST_ROUTE = '/pokemons/'
export const POKEMON_SINGLE_ROUTE = '/pokemon/'
export const POKEDEX_PAGE_ROUTE = '/pokedex/'
export const POKEMON_IMAGE_BASE_URL = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon'
